-- ==========================================
-- SKRIP DATABASE SUPABASE - MASTER TEMPLATE
-- ==========================================
-- Jalankan skrip ini di menu "SQL Editor" pada dasbor Supabase Anda.
-- ==========================================

-- 1. Tabel Kategori
CREATE TABLE IF NOT EXISTS public.kategori (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_kategori VARCHAR(100) NOT NULL UNIQUE,
  slug VARCHAR(100) NOT NULL UNIQUE,
  tipe VARCHAR(50) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabel Produk
CREATE TABLE IF NOT EXISTS public.produk (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kategori_id BIGINT REFERENCES public.kategori(id) ON DELETE RESTRICT,
  nama_produk VARCHAR(150) NOT NULL,
  slug VARCHAR(150) NOT NULL UNIQUE,
  deskripsi TEXT,
  harga DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  stok INT NOT NULL DEFAULT 0,
  url_gambar VARCHAR(255),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabel Berita
CREATE TABLE IF NOT EXISTS public.berita (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kategori_id BIGINT REFERENCES public.kategori(id) ON DELETE RESTRICT,
  judul VARCHAR(200) NOT NULL,
  slug VARCHAR(200) NOT NULL UNIQUE,
  konten TEXT NOT NULL,
  url_gambar VARCHAR(255),
  status VARCHAR(20) DEFAULT 'DRAFT',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabel Galeri
DROP TABLE IF EXISTS public.galeri CASCADE;
CREATE TABLE public.galeri (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  media_type VARCHAR(20) DEFAULT 'image',
  title VARCHAR(200) NOT NULL,
  caption TEXT,
  url TEXT NOT NULL,
  date VARCHAR(50),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabel Profil Koperasi
CREATE TABLE IF NOT EXISTS public.profil_koperasi (
  id BIGINT PRIMARY KEY DEFAULT 1,
  nama_koperasi VARCHAR(150) NOT NULL,
  singkatan VARCHAR(50) NOT NULL,
  logo_url VARCHAR(255),
  deskripsi TEXT,
  visi TEXT,
  misi TEXT,
  legal_json JSONB,
  kontak_json JSONB,
  pengurus_json JSONB,
  layanan_json JSONB,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Mengaktifkan Row Level Security (RLS)
ALTER TABLE public.kategori ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.produk ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.berita ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.galeri ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profil_koperasi ENABLE ROW LEVEL SECURITY;

-- Kebijakan Keamanan (Policies)
-- Publik: Bisa membaca (SELECT) semua tabel.
CREATE POLICY "Public Read Kategori" ON public.kategori FOR SELECT USING (true);
CREATE POLICY "Public Read Produk" ON public.produk FOR SELECT USING (true);
CREATE POLICY "Public Read Berita" ON public.berita FOR SELECT USING (true);
CREATE POLICY "Public Read Galeri" ON public.galeri FOR SELECT USING (true);
CREATE POLICY "Public Read Profil" ON public.profil_koperasi FOR SELECT USING (true);

-- Admin (Autentikasi): Bisa melakukan apa saja (INSERT, UPDATE, DELETE).
CREATE POLICY "Admin All Kategori" ON public.kategori FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin All Produk" ON public.produk FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin All Berita" ON public.berita FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin All Galeri" ON public.galeri FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin All Profil" ON public.profil_koperasi FOR ALL USING (auth.role() = 'authenticated');

-- 6. Insert Data Bawaan (Default) Profil Koperasi
INSERT INTO public.profil_koperasi 
  (id, nama_koperasi, singkatan, logo_url, deskripsi, visi, legal_json, kontak_json, pengurus_json, layanan_json)
VALUES (
  1,
  'Koperasi Tani Pangan Mandiri',
  'KOPDES',
  'https://via.placeholder.com/150x150.png?text=Logo+Kopdes',
  'Koperasi desa yang berfokus pada ketahanan pangan dan kesejahteraan petani lokal.',
  'Menjadi pilar ketahanan pangan desa dan memajukan kesejahteraan petani.',
  '{"badanHukum": "No. 123/BH/KDK/2020", "wilayahKerja": "Kecamatan Nusantara"}',
  '{"alamat": "", "googleMapsLink": "", "googleMapsEmbedUrl": "", "telepon": "", "whatsapp": "", "email": "", "jamKerja": "", "sosialMedia": {}}',
  '{"ketua": {"nama": "", "foto": ""}, "sekretaris": {"nama": "", "foto": ""}, "bendahara": {"nama": "", "foto": ""}, "pengawas": {"nama": "", "foto": ""}}',
  '[{"id": "simpan-pinjam", "title": "Unit Simpan Pinjam Desa", "description": "Layanan simpanan anggota dan pembiayaan modal kerja dengan tata kelola adil, transparan.", "features": ["Simpanan Pokok & Wajib", "Pembiayaan Modal Usaha", "Proses Cepat & Transparan"]}, {"id": "kios-saprotan", "title": "Kios Saprotan & Sembako Desa", "description": "Penyediaan benih unggul, pupuk resmi, pestisida, dan pasokan bahan pokok dengan harga distributor bagi anggota.", "features": ["Harga Distributor Resmi", "Skema Bayar Panen", "Jaminan Kualitas Mutu"]}, {"id": "offtaker-panen", "title": "Offtaker & Pemasaran Panen", "description": "Penyerapan langsung hasil pertanian dan perkebunan warga desa untuk disalurkan ke jaringan pasar induk.", "features": ["Harga Acuan Adil", "Penimbangan Digital Jujur", "Pembayaran Tepat Waktu"]}]'
) ON CONFLICT (id) DO NOTHING;

-- 7. Membuat Storage Bucket untuk Upload Gambar
INSERT INTO storage.buckets (id, name, public) VALUES ('kopdes_images', 'kopdes_images', true) ON CONFLICT DO NOTHING;
CREATE POLICY "Public read images" ON storage.objects FOR SELECT USING (bucket_id = 'kopdes_images');
CREATE POLICY "Admin all images" ON storage.objects FOR ALL USING (bucket_id = 'kopdes_images' AND auth.role() = 'authenticated');
