-- ==========================================
-- SKRIP DATABASE SUPABASE - PROFIL PERUSAHAAN
-- ==========================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Tabel Kategori
CREATE TABLE IF NOT EXISTS public.kategori (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_kategori VARCHAR(100) NOT NULL UNIQUE,
  slug VARCHAR(100) NOT NULL UNIQUE,
  tipe VARCHAR(50) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabel Produk
CREATE TABLE IF NOT EXISTS public.produk (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kategori_id BIGINT REFERENCES public.kategori(id) ON DELETE RESTRICT,
  nama_produk VARCHAR(150) NOT NULL,
  slug VARCHAR(150) NOT NULL UNIQUE,
  deskripsi TEXT,
  harga DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  stok INT NOT NULL DEFAULT 0,
  url_gambar VARCHAR(255),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabel Berita
CREATE TABLE IF NOT EXISTS public.berita (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kategori_id BIGINT REFERENCES public.kategori(id) ON DELETE RESTRICT,
  judul VARCHAR(200) NOT NULL,
  slug VARCHAR(200) NOT NULL UNIQUE,
  konten TEXT NOT NULL,
  url_gambar VARCHAR(255),
  status VARCHAR(20) DEFAULT 'DRAFT',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabel Galeri
CREATE TABLE IF NOT EXISTS public.galeri (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  media_type VARCHAR(20) DEFAULT 'image',
  title VARCHAR(200) NOT NULL,
  caption TEXT,
  url TEXT NOT NULL,
  date VARCHAR(50),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabel Profil Perusahaan
CREATE TABLE IF NOT EXISTS public.profil_perusahaan (
  id BIGINT PRIMARY KEY DEFAULT 1,
  nama_perusahaan VARCHAR(150) NOT NULL,
  singkatan VARCHAR(50) NOT NULL,
  logo_url VARCHAR(255),
  deskripsi TEXT,
  visi TEXT,
  misi TEXT,
  legal_json JSONB,
  kontak_json JSONB,
  pengurus_json JSONB,
  layanan_json JSONB,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Mengaktifkan Row Level Security (RLS)
ALTER TABLE public.kategori ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.produk ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.berita ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.galeri ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profil_perusahaan ENABLE ROW LEVEL SECURITY;

-- Kebijakan Keamanan (Policies)
DROP POLICY IF EXISTS "Public Read Kategori" ON public.kategori;
CREATE POLICY "Public Read Kategori" ON public.kategori FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Produk" ON public.produk;
CREATE POLICY "Public Read Produk" ON public.produk FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Berita" ON public.berita;
CREATE POLICY "Public Read Berita" ON public.berita FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Galeri" ON public.galeri;
CREATE POLICY "Public Read Galeri" ON public.galeri FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Profil" ON public.profil_perusahaan;
CREATE POLICY "Public Read Profil" ON public.profil_perusahaan FOR SELECT USING (true);

-- Admin (Autentikasi): Akses Penuh
DROP POLICY IF EXISTS "Admin All Kategori" ON public.kategori;
CREATE POLICY "Admin All Kategori" ON public.kategori FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admin All Produk" ON public.produk;
CREATE POLICY "Admin All Produk" ON public.produk FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admin All Berita" ON public.berita;
CREATE POLICY "Admin All Berita" ON public.berita FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admin All Galeri" ON public.galeri;
CREATE POLICY "Admin All Galeri" ON public.galeri FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admin All Profil" ON public.profil_perusahaan;
CREATE POLICY "Admin All Profil" ON public.profil_perusahaan FOR ALL USING (auth.role() = 'authenticated');

-- 6. Insert Data Bawaan (Default) Profil Perusahaan Umum
INSERT INTO public.profil_perusahaan 
  (id, nama_perusahaan, singkatan, logo_url, deskripsi, visi, misi, legal_json, kontak_json, pengurus_json, layanan_json)
VALUES (
  1,
  'PT Profil Perusahaan Nusantara',
  'PROFIL PERUSAHAAN',
  'https://via.placeholder.com/150x150.png?text=Logo+Company',
  'Perusahaan profesional dan terpercaya yang berkomitmen memberikan solusi terintegrasi dan berkualitas tinggi untuk memenuhi kebutuhan mitra dan pelanggan.',
  'Menjadi perusahaan terkemuka yang inovatif, berdaya saing global, dan memberikan dampak positif berkelanjutan.',
  'Memberikan produk dan layanan terbaik dengan standar keunggulan operasional tinggi serta membangun kemitraan yang solid.',
  '{"badanHukum": "AHU-0012845.AH.01.01.Tahun 2024", "wilayahKerja": "Nasional & Regional"}',
  '{"alamat": "", "googleMapsLink": "", "googleMapsEmbedUrl": "", "telepon": "", "whatsapp": "", "email": "", "jamKerja": "Senin - Jumat: 08.00 - 17.00 WIB", "sosialMedia": {}}',
  '{"ketua": {"nama": "", "foto": "", "jabatan": "Direktur Utama"}, "sekretaris": {"nama": "", "foto": "", "jabatan": "Sekretaris Perusahaan"}, "bendahara": {"nama": "", "foto": "", "jabatan": "Direktur Keuangan"}, "pengawas": {"nama": "", "foto": "", "jabatan": "Komisaris Utama"}}',
  '[{"id": "konsultasi", "title": "Konsultasi & Solusi Bisnis", "description": "Layanan konsultasi profesional untuk membantu mengoptimalkan strategi dan operasional bisnis Anda.", "features": ["Analisis Komprehensif", "Solusi Tepat Sasaran", "Didukung Tenaga Ahli"]}, {"id": "pengadaan", "title": "Pengadaan & Distribusi", "description": "Penyediaan barang dan rantai pasok dengan jaminan mutu terbaik dan pengiriman tepat waktu.", "features": ["Jaringan Luas", "Kualitas Terstandarisasi", "Harga Kompetitif"]}, {"id": "kemitraan", "title": "Kemitraan Strategis", "description": "Kolaborasi strategis untuk memperluas jangkauan pasar dan pertumbuhan bisnis berkelanjutan.", "features": ["Kerjasama Transparan", "Dukungan Berkelanjutan", "Manfaat Timbal Balik"]}]'
) ON CONFLICT (id) DO NOTHING;

-- 7. Storage Bucket untuk Upload Media
INSERT INTO storage.buckets (id, name, public) VALUES ('profile_images', 'profile_images', true) ON CONFLICT DO NOTHING;

DROP POLICY IF EXISTS "Public read images" ON storage.objects;
CREATE POLICY "Public read images" ON storage.objects FOR SELECT USING (bucket_id = 'profile_images');

DROP POLICY IF EXISTS "Admin all images" ON storage.objects;
CREATE POLICY "Admin all images" ON storage.objects FOR ALL USING (bucket_id = 'profile_images' AND auth.role() = 'authenticated');